version: '3.7'

services:
  app:
    build: 
       context: .
       dockerfile: Dockerfile
    image: sandboxapp
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www

  webserver:
    build:
       context: .
       dockerfile: Dockerfile1
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
       - ./:/var/www
       - ./src/nginx/:/etc/nginx/conf.d/
    depends_on:
       - app       
